### PR TITLE
Adjusted Renovate config

### PR DESCRIPTION
**Pull request by awanlin**
Updated the Renovate config to match changes suggested by https://github.com/backstage/backstage/pull/22479

### CODE REVIEW

**Comment by secustor** [comment]
Instead of dropping pinning I suggest to use `automerge`. 
With [`automergeType: branch`](https://docs.renovatebot.com/configuration-options/#automergetype) you can only surface PRs if the pipeline is failing. 
From a noise level it does not make difference as you will still get updates for each of your dependencies. 

The [noise reduction](https://docs.renovatebot.com/noise-reduction/) guide is also a good read to reduce your mental load of keeping up to date.

Your packageRule can also be simplified using templating: 
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:best-practices", ":gitSignOff"],
  "ignorePresets": [":pinDevDependencies", ":pinDigest"],
  "postUpdateOptions": ["yarnDedupeHighest"],
  "rangeStrategy": "update-lockfile",
  "labels": ["dependencies"],
  "packageRules": [
    {
      "matchUpdateTypes": ["major", "minor", "patch"],
      "addLabels": ["{{ updateType }}"]
    },
    {
      "matchSourceUrls": ["https://github.com/yarnpkg/berry"],
      "enabled": false
    },
    {
      "matchPackagePatterns": ["@backstage"],
      "matchManagers": ["npm"],
      "enabled": false
    }
  ],
  "osvVulnerabilityAlerts": true,
  "vulnerabilityAlerts": {
    "addLabels": ["security"],
    "enabled": true
  }
}
```

**Comment by awanlin** [comment]
Thanks for the feedback and links @secustor! I'm not sure I'm at the place where auto merge makes sense, perhaps in the future. I did make the changes to use templating, that's nice, and  I'm going to keep `pinDigest` so we can see what the results are like.

**Review by freben — APPROVED** [review]
let's try!

**Comment by freben** [comment]
@secustor i tried disabling pinning in https://github.com/backstage/backstage/blob/645e1cbda55800e28d574a0f1823dce8073611ee/.github/renovate.json5#L12 but seems it still insists on pinning at least docker things https://github.com/backstage/backstage/pull/23026

**Comment by awanlin** [comment]
Thanks @freben 🚀

**Pull request merged**
